### ISSUE TITLE
DNN sample doesn't compile with GCC 6.3.1

### ISSUE THREAD

**Issue by alheinecke** [hfp/libxsmm#134]
With gcc 6.3.1 (FC25) I see the following error when compiling samples/dnn with "make realclean && make"

cc -g -Wall -Wno-unused-function -Wno-attributes -fpic -O2 -funroll-loops -ftree-vectorize -ffast-math -fopenmp -pthread -DNDEBUG -D_REENTRANT -I. -I../../include -march=core-avx2 -c /home/heinecke/Projects/LIBXSMM_workspace/libxsmm_github/samples/dnn/layer_example_f32.c -o layer_example_f32-c.o
cc -o layer_example_f32 ./layer_example_f32-c.o \
	../../lib/libxsmm.a \
	../../lib/libxsmmnoblas.a \
	 -fpic -fopenmp -Wl,--as-needed -lrt -ldl -Wl,--no-as-needed -Wl,--as-needed -lstdc++ -Wl,--no-as-needed -pthread
../../lib/libxsmm.a(libxsmm_sync.o): In function `libxsmm_barrier_create':
libxsmm_sync.c:(.text+0x49): undefined reference to `__log2_finite'
collect2: error: ld returned 1 exit status
Makefile:74: recipe for target 'layer_example_f32' failed
make: *** [layer_example_f32] Error 1

**Comment by hfp** [comment]
( I will also setup GCC 6.x CI )

**Comment by hfp** [comment]
( Please reopen if it is not resolved. )
